print('Now I need money')
# input()
# input('Give me money: ')
# money=input('give me mny: ')
# print("here is you money ",money)
firstMoney= input('kodom ali: ')
secondMoney = input('bappa raj: ')
firstMoney_int=int(firstMoney)
secondMoney_int=int(secondMoney)
sum=firstMoney_int+secondMoney_int
print(sum)